#!/usr/bin/env python3
"""Rasterize a curated Chinese subset into main/ui_font_cjk.c, matching
main/display.c's F_BODY (17px) metrics so mixed ASCII+CJK captions line up.

Same technique as gen_ui_font.py (anti-aliased 8-bit alpha glyphs from a
TrueType face via Pillow), but sparse instead of dense: CJK codepoints are
scattered across U+4E00.., so this emits a codepoint-sorted table that
display.c binary-searches, instead of gen_ui_font.py's flat 0..255 array.

Noto Sans SC is SIL Open Font License 1.1 -- same license as Inter, so
shipping the rasterized glyphs is fine (see gen_ui_font.py's note).

    pip install pillow
    python3 tools/gen_cjk_font.py            # downloads Noto Sans SC into tools/.cache
    python3 tools/gen_cjk_font.py --font /path/to/NotoSansSC.ttf

This is a CURATED SUBSET, not full CJK coverage -- full Unicode Han coverage
(tens of thousands of glyphs) does not fit this chip's flash. CHARS below
covers common greeting/ordering vocabulary for a Malaysian food-ordering
kiosk: numbers, pronouns/grammar, courtesy phrases, and the Chinese names for
this menu's items (see agents/restaurant/menu.json). Anything spoken outside
this set still transcribes and reaches the agent correctly -- it just falls
back to '?' on THIS screen only (see resolve_glyph() in display.c). Extend
coverage by adding characters to CHARS and re-running; duplicates are fine,
the script dedupes.
"""

import argparse
import os
import sys
import urllib.request

from PIL import Image, ImageDraw, ImageFont

NOTO_SANS_SC_URL = ("https://raw.githubusercontent.com/google/fonts/main/"
                     "ofl/notosanssc/NotoSansSC%5Bwght%5D.ttf")

# Must match gen_ui_font.py's F_BODY entry exactly (px size + weight) so a
# mixed-script line has consistent glyph height/baseline.
SIZE, WEIGHT = 17, "Regular"

# ---- curated subset ---------------------------------------------------------
# Numbers / quantities
NUMBERS = "零一二三四五六七八九十百千两半几"
UNITS = "个杯碗份包份条块片粒"
# Pronouns, grammar particles, question words
GRAMMAR = ("我你他她它们的了吗呢吧啊哦是不没有要请问这那个什么样"
           "还多少点可以给来去走还有再一些点儿之和跟对啦哈嗯")
# Ordering / transaction verbs and common phrases
ORDER = ("买卖打包堂食吃喝叫换加减够完成确定好谢谢你好再见麻烦"
         "钱共总帮先等一下慢急快先生小姐老板")
# Food & drink -- Chinese names/loanwords used at a Malaysian mamak stall,
# covering agents/restaurant/menu.json (nasi lemak, nasi goreng, mee goreng,
# maggi goreng, char kuey teow, roti canai, roti telur, ayam goreng, satay
# ayam, teh tarik, teh o ais, kopi o, milo ais, milo dinosaur, limau ais,
# sirap bandung) plus generic staples so nearby words a customer might say
# also render.
FOOD = ("椰浆饭炒面粿条印度煎饼鸡蛋炸鸡沙爹肉牛猪鱼虾豆腐青菜汤饭面"
        "包水果汁茶奶咖啡冰热甜酸辣咸淡糖美禄龙拉红青柠水丝")
CHARS = NUMBERS + UNITS + GRAMMAR + ORDER + FOOD


def load_face(path, size, weight):
    f = ImageFont.truetype(path, size)
    try:
        f.set_variation_by_name(weight)
    except Exception:
        axes = {"Thin": 100, "ExtraLight": 200, "Light": 300, "Regular": 400,
                "Medium": 500, "SemiBold": 600, "Bold": 700, "ExtraBold": 800,
                "Black": 900}
        try:
            f.set_variation_by_axes([float(axes[weight])])
        except Exception:
            print(f"  ! no variation support, using default weight for {weight}")
    return f


def render(face, chars):
    """One sparse glyph table + alpha blob, sorted by codepoint so display.c
    can binary-search it. Coordinates match gen_ui_font.py's convention:
    dx from the pen, dy down from the top of the line box."""
    pad = SIZE * 2
    canvas = SIZE * 4
    entries, blob = [], bytearray()
    seen = set()

    for ch in sorted(set(chars)):
        cp = ord(ch)
        if cp in seen:
            continue
        seen.add(cp)
        adv = int(round(face.getlength(ch)))
        img = Image.new("L", (canvas, canvas), 0)
        ImageDraw.Draw(img).text((pad, pad), ch, font=face, fill=255, anchor="la")
        bbox = img.getbbox()
        if bbox is None:
            entries.append((cp, 0, 0, 0, 0, adv, 0))
            continue
        x0, y0, x1, y1 = bbox
        entries.append((cp, x1 - x0, y1 - y0, x0 - pad, y0 - pad, adv, len(blob)))
        blob += img.crop(bbox).tobytes()

    entries.sort(key=lambda e: e[0])   # already sorted via sorted(set(chars)), belt+braces
    return entries, blob


def emit(out_path, entries, blob):
    with open(out_path, "w") as out:
        out.write(f"// Generated by tools/{os.path.basename(__file__)} -- do not edit.\n")
        out.write("// Noto Sans SC (SIL Open Font License 1.1), rasterized to 8-bit alpha.\n")
        out.write("// Curated subset -- see gen_cjk_font.py's CHARS for what's covered.\n")
        out.write('#include "ui_font.h"\n\n')

        out.write(f"static const uint8_t f_body_cjk_alpha[{len(blob)}] = {{\n")
        for i in range(0, len(blob), 24):
            out.write("    " + ",".join(str(b) for b in blob[i:i + 24]) + ",\n")
        out.write("};\n\n")

        out.write(f"static const cjk_glyph_t f_body_cjk_glyphs[{len(entries)}] = {{\n")
        for cp, w, h, dx, dy, adv, off in entries:
            ch = chr(cp)
            out.write(f"    {{0x{cp:04X}, {{{w},{h},{dx},{dy},{adv},{off}}}}}, // {ch}\n")
        out.write("};\n\n")

        out.write("const cjk_font_t F_BODY_CJK = {\n"
                   "    .glyphs = f_body_cjk_glyphs, .alpha = f_body_cjk_alpha,\n"
                   f"    .count = {len(entries)},\n"
                   "};\n")

    size = os.path.getsize(out_path)
    print(f"wrote {out_path} ({size} bytes, {len(entries)} glyphs, "
          f"{len(blob) / 1024:.1f} KB alpha)")


def main():
    here = os.path.dirname(os.path.abspath(__file__))
    ap = argparse.ArgumentParser()
    ap.add_argument("--font", default=os.path.join(here, ".cache", "NotoSansSC.ttf"))
    ap.add_argument("--out", default=os.path.join(here, os.pardir, "main", "ui_font_cjk.c"))
    args = ap.parse_args()

    if not os.path.exists(args.font):
        os.makedirs(os.path.dirname(args.font), exist_ok=True)
        print(f"downloading Noto Sans SC -> {args.font}")
        urllib.request.urlretrieve(NOTO_SANS_SC_URL, args.font)

    face = load_face(args.font, SIZE, WEIGHT)
    entries, blob = render(face, CHARS)
    print(f"F_BODY_CJK  {WEIGHT} {SIZE}px  {len(entries)} glyphs  "
          f"alpha={len(blob) / 1024:.1f} KB")

    out_path = os.path.abspath(args.out)
    emit(out_path, entries, blob)
    return 0


if __name__ == "__main__":
    sys.exit(main())
