#!/usr/bin/env python3
"""Rasterize Inter into the anti-aliased glyph atlases used by main/display.c.

The box has no LVGL (see main/idf_component.yml for why), so display.c draws
straight into a framebuffer and needs its fonts as plain C data. This script
renders ASCII 0x20..0x7E at the five sizes the UI uses and emits
main/ui_font.c: one 8-bit alpha blob plus a glyph table per font.

    pip install pillow
    python3 tools/gen_ui_font.py            # downloads Inter into tools/.cache
    python3 tools/gen_ui_font.py --font /path/to/Inter.ttf

Inter is SIL Open Font License 1.1, so shipping the rasterized glyphs inside
the firmware is fine. Only re-run this when a size or the face changes; the
generated ui_font.c is committed so a normal build needs no Python.
"""

import argparse
import os
import sys
import urllib.request

from PIL import Image, ImageDraw, ImageFont

INTER_URL = ("https://raw.githubusercontent.com/google/fonts/main/ofl/inter/"
             "Inter%5Bopsz%2Cwght%5D.ttf")

FIRST, LAST = 0x20, 0x7E

# (C name, px size, weight, extra tracking in px applied after every glyph)
FONTS = [
    ("F_LABEL", 13, "SemiBold", 0),   # chips, small captions
    ("F_BODY",  17, "Regular",  0),   # wrapped transcript text
    ("F_ROW",   18, "SemiBold", 0),   # order rows + prices
    ("F_HEAD",  26, "Bold",    -1),   # titles, TOTAL, buttons
    ("F_HERO",  50, "Bold",    -2),   # the one big word on a status screen
]


def load_face(path, size, weight):
    f = ImageFont.truetype(path, size)
    try:
        f.set_variation_by_name(weight)
    except Exception:
        # Static instance, or a Pillow/FreeType without variation support.
        axes = {"Thin": 100, "ExtraLight": 200, "Light": 300, "Regular": 400,
                "Medium": 500, "SemiBold": 600, "Bold": 700, "ExtraBold": 800,
                "Black": 900}
        try:
            # Inter's axes are (opsz, wght); opsz tracks the pixel size.
            f.set_variation_by_axes([float(size), float(axes[weight])])
        except Exception:
            print(f"  ! no variation support, using default weight for {weight}")
    return f


def render(face, size):
    """One glyph table + alpha blob. Coordinates are relative to the line box:
    dx from the pen, dy down from the top of the line box (the ascender)."""
    pad = size * 2
    canvas = size * 4
    ascent, descent = face.getmetrics()
    glyphs, blob = [], bytearray()

    for code in range(FIRST, LAST + 1):
        ch = chr(code)
        adv = int(round(face.getlength(ch)))
        img = Image.new("L", (canvas, canvas), 0)
        ImageDraw.Draw(img).text((pad, pad), ch, font=face, fill=255, anchor="la")
        bbox = img.getbbox()
        if bbox is None:                      # space and friends: advance only
            glyphs.append((0, 0, 0, 0, adv, 0))
            continue
        x0, y0, x1, y1 = bbox
        glyphs.append((x1 - x0, y1 - y0, x0 - pad, y0 - pad, adv, len(blob)))
        blob += img.crop(bbox).tobytes()

    return glyphs, blob, ascent, descent


def emit(out, path, fonts):
    out.write(f"// Generated by tools/{os.path.basename(__file__)} -- do not edit.\n")
    out.write("// Inter (SIL Open Font License 1.1), rasterized to 8-bit alpha.\n")
    out.write('#include "ui_font.h"\n')

    for name, size, weight, track, glyphs, blob, ascent, descent in fonts:
        low = name.lower()
        out.write(f"\n// {name}: Inter {weight} {size}px, "
                  f"{len(glyphs)} glyphs, {len(blob)} bytes of alpha\n")
        out.write(f"static const uint8_t {low}_alpha[{len(blob)}] = {{\n")
        for i in range(0, len(blob), 24):
            out.write("    " + ",".join(str(b) for b in blob[i:i + 24]) + ",\n")
        out.write("};\n")

        out.write(f"static const ui_glyph_t {low}_glyphs[{len(glyphs)}] = {{\n")
        for code, (w, h, dx, dy, adv, off) in enumerate(glyphs, start=FIRST):
            out.write(f"    {{{w},{h},{dx},{dy},{adv},{off}}}, // '{chr(code)}'\n"
                      if chr(code) not in "\\'" else
                      f"    {{{w},{h},{dx},{dy},{adv},{off}}}, // 0x{code:02X}\n")
        out.write("};\n")

        line_h = ascent + descent
        out.write(f"const ui_font_t {name} = {{\n"
                  f"    .glyphs = {low}_glyphs, .alpha = {low}_alpha,\n"
                  f"    .first = 0x{FIRST:02X}, .last = 0x{LAST:02X},\n"
                  f"    .ascent = {ascent}, .line_h = {line_h}, .track = {track},\n"
                  f"}};\n")

    print(f"wrote {path} ({os.path.getsize(path) if os.path.exists(path) else 0} bytes)")


def main():
    here = os.path.dirname(os.path.abspath(__file__))
    ap = argparse.ArgumentParser()
    ap.add_argument("--font", default=os.path.join(here, ".cache", "Inter.ttf"))
    ap.add_argument("--out", default=os.path.join(here, os.pardir, "main", "ui_font.c"))
    args = ap.parse_args()

    if not os.path.exists(args.font):
        os.makedirs(os.path.dirname(args.font), exist_ok=True)
        print(f"downloading Inter -> {args.font}")
        urllib.request.urlretrieve(INTER_URL, args.font)

    built = []
    for name, size, weight, track in FONTS:
        face = load_face(args.font, size, weight)
        glyphs, blob, ascent, descent = render(face, size)
        print(f"{name:8} {weight:9} {size:>3}px  ascent={ascent:>3} "
              f"line_h={ascent + descent:>3}  alpha={len(blob) / 1024:6.1f} KB")
        built.append((name, size, weight, track, glyphs, blob, ascent, descent))

    out_path = os.path.abspath(args.out)
    with open(out_path, "w") as out:
        emit(out, out_path, built)
    total = sum(len(b[5]) for b in built)
    print(f"total alpha: {total / 1024:.1f} KB of flash")
    return 0


if __name__ == "__main__":
    sys.exit(main())
